wandb_version: 1

object:
  desc: null
  value: fine-tune
id:
  desc: null
  value: ft-EB4Kc0Juv3ip5MQ0AYxSrkI2
hyperparams:
  desc: null
  value:
    n_epochs: 4
    batch_size: 1
    prompt_loss_weight: 0.01
    learning_rate_multiplier: 0.1
organization_id:
  desc: null
  value: org-4MIbwq6pGkIxyYGJHzTJGH3u
model:
  desc: null
  value: curie
training_files:
  desc: null
  value:
    object: file
    id: file-ec6Gnqsp3vSOC8IQGP8LbrDz
    purpose: fine-tune
    filename: prepocess/prepocessed_prepared_train.jsonl
    bytes: 256810
    created_at: 1686506232
    status: processed
    status_details: null
validation_files:
  desc: null
  value:
    object: file
    id: file-YyWxPCOLCsOOerHhWchEklkR
    purpose: fine-tune
    filename: prepocess/prepocessed_prepared_valid.jsonl
    bytes: 66374
    created_at: 1686506234
    status: processed
    status_details: null
result_files:
  desc: null
  value:
    object: file
    id: file-DfNOZvnKaLa6UTsubl4ICnCU
    purpose: fine-tune-results
    filename: compiled_results.csv
    bytes: 180851
    created_at: 1686507031
    status: processed
    status_details: null
created_at:
  desc: null
  value: '2023-06-12T02:57:14'
updated_at:
  desc: null
  value: 1686507031
status:
  desc: null
  value: succeeded
fine_tuned_model:
  desc: null
  value: curie:ft-personal-2023-06-11-18-10-30
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686565308.246475
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.8.16
      5: 0.15.3
      8:
      - 3
      - 5
n_train:
  desc: null
  value: 790
n_valid:
  desc: null
  value: 198
