wandb_version: 1

object:
  desc: null
  value: fine-tune
id:
  desc: null
  value: ft-sxu7WW3pntRViFCedrEAFyA7
hyperparams:
  desc: null
  value:
    n_epochs: 4
    batch_size: 8
    prompt_loss_weight: 0.01
    learning_rate_multiplier: 0.1
organization_id:
  desc: null
  value: org-4MIbwq6pGkIxyYGJHzTJGH3u
model:
  desc: null
  value: curie
training_files:
  desc: null
  value:
    object: file
    id: file-80DIHez2FkU7EXj0OrIgWIiv
    purpose: fine-tune
    filename: prepocess/causes_prepared_train.jsonl
    bytes: 596189
    created_at: 1691266546
    status: processed
    status_details: null
validation_files:
  desc: null
  value:
    object: file
    id: file-FErnoHCsbHFTwGANF8nERteA
    purpose: fine-tune
    filename: prepocess/causes_prepared_valid.jsonl
    bytes: 122694
    created_at: 1691266549
    status: processed
    status_details: null
result_files:
  desc: null
  value:
    object: file
    id: file-wJ3WfXFgkwVJome9GYU7l5BT
    purpose: fine-tune-results
    filename: compiled_results.csv
    bytes: 166466
    created_at: 1691277771
    status: processed
    status_details: null
created_at:
  desc: null
  value: '2023-08-06T05:15:49'
updated_at:
  desc: null
  value: 1691277772
status:
  desc: null
  value: succeeded
fine_tuned_model:
  desc: null
  value: curie:ft-personal-2023-08-05-23-22-50
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691289027.085276
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.8.16
      5: 0.15.3
      8:
      - 3
      - 5
n_train:
  desc: null
  value: 4786
n_valid:
  desc: null
  value: 1000
